import blogImage1 from './images/blogImage1.jpg'
import blogImage2 from './images/blogImage2.jpg'
import blogImage3 from './images/blogImage3.jpg'

import productImage from './images/productImage.jpg';

export const blogDetails = [
  {
    blogIndex: 1,
    img: blogImage1,
    title: "Understanding the Importance of Web Accessibility",
    description:
      "Web accessibility is crucial for providing equal access and opportunities to people with disabilities.",
    date: "October 13, 2023",
  },
  {
    blogIndex: 2,
    img: blogImage2,
    title: "A Comprehensive Guide to Dealing with Gallstones",
    description:
      "Gallstones are the hardened substance that gets deposited inside the gallbladder and can cause severe pain.",
    date: "October 13, 2023",
  },
  {
    blogIndex: 3,
    img: blogImage3,
    title: "The Science Behind Attractiveness",
    description:
      "Several researches prove that our eyes play a significant role in the perception of attractiveness.",
    date: "October 13, 2023",
  },
  {
    blogIndex: 4,
    img: blogImage1,
    title: "The Impact of Visual Design on User Experience",
    description:
      "Visual design principles are instrumental in creating a positive user experience on websites and apps.",
    date: "June 13, 2021",
  },
  {
    blogIndex: 5,
    img: blogImage2,
    title: "Tips for Creating Engaging Website Content",
    description:
      "Effective content creation strategies can keep your website visitors engaged and coming back for more.",
    date: "April 13, 2022",
  },
  {
    blogIndex: 6,
    img: blogImage3,
    title: "Mastering the Art of Effective Storytelling",
    description:
      "Conveying information through storytelling is an age-old technique that remains impactful in the digital age.",
    date: "October 13, 2023",
  },
];

export const productsDetails = [
  {
    prodIndex: 1,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 2,
    prodImage: "https://sharangdhar.com/cdn/shop/products/ashwagandha.jpg?v=1634966548",
    category: "Capsule",
    prodName: "Turmeric",
    star: "4",
    oldPrice: 99,
    newPrice: 39,
  },
  {
    prodIndex: 3,
    prodImage: "https://oraah.in/cdn/shop/files/Ashwagandha-Powder-_1.jpg?v=1687346530",
    category: "Tablet",
    prodName: "Neem",
    star: "3.5",
    oldPrice: 89,
    newPrice: 49,
  },
  {
    prodIndex: 4,
    prodImage: "https://bixabotanical.com/cdn/shop/files/Ashwagandha1_1024x1024.jpg?v=1697280416",
    category: "Liquid",
    prodName: "Brahmi",
    star: "5",
    oldPrice: 135,
    newPrice: 69,
  },
  {
    prodIndex: 5,
    prodImage: "https://m.media-amazon.com/images/I/71PzxxB1k6L._AC_UF350,350_QL80_.jpg",
    category: "Powder",
    prodName: "Amla",
    star: "4.5",
    oldPrice: 95,
    newPrice: 45,
  },
  {
    prodIndex: 6,
    prodImage: "https://rukminim2.flixcart.com/image/850/1000/kqidx8w0/body-pain-relief/e/y/j/50-ashwagandha-powder-for-height-growth-stamina-booster-strees-original-imag4g3etwgvhfz7.jpeg?q=90",
    category: "Capsule",
    prodName: "Moringa",
    star: "4.2",
    oldPrice: 105,
    newPrice: 59,
  },
  {
    prodIndex: 7,
    prodImage: "https://drvaidyas.com/cdn/shop/files/Shuddha-Ashwagandha-Pack-of-2_large.jpg?v=1698217318",
    category: "Liquid",
    prodName: "Tulsi",
    star: "4.1",
    oldPrice: 100,
    newPrice: 50,
  },
  {
    prodIndex: 8,
    prodImage: "https://www.curegarden.in/wp-content/uploads/2020/11/Artboard-1-copy-7.png",
    category: "Tablet",
    prodName: "Ginger",
    star: "3.8",
    oldPrice: 80,
    newPrice: 44,
  },
  {
    prodIndex: 9,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "4.7",
    oldPrice: 115,
    newPrice: 49,
  },
  {
    prodIndex: 10,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Capsule",
    prodName: "Fenugreek",
    star: "4.3",
    oldPrice: 99,
    newPrice: 52,
  },
  {
    prodIndex: 11,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 12,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 13,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 14,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 15,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 16,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 17,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: "https://saptamveda.com/cdn/shop/products/AshwagandhaPlainthumbnail.jpg?v=1648782669",
    category: "Powder",
    prodName: "Ashwagandha",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
];
